# Argvus palette
# ---
# bg         "#111316"
# bg-2       "#1D1D23"
# ui         "#262933"
# ui-2       "#333647"
# ui-3       "#404552"
# tx-3       "#718994"
# tx-2       "#B0BFCB"
# tx         "#DFE5EA"
# red-400     "#4C3A3B" re
# orange-400  "#695B57" or
# yellow-400  "#B0BFCB" ye
# yellow-600  "#695B57" ye-2
# green-400   "#595959" gr
# cyan-400    "#595959" cy
# cyan-600    "#2E2E2E" cy-2
# cyan-700    "#2E2E2E" cy-700
# cyan-900    "#1D1D23" cy-900
# blue-400    "#595959" bl
# purple-400  "#8A8A8A" pu
# magenta-400 "#4C3A3B" ma

[app]
overall = { bg = "#111316" } # bg

[mgr]
cwd = { fg = "#DFE5EA", bold = true } # tx

# Find
find_keyword = { fg = "#595959", reversed = true } # cy
find_position = { fg = "#595959", bold = true, italic = true } # cy

# Marker
marker_copied = { fg = "#595959", bg = "#595959" } # gr, gr
marker_cut = { fg = "#4C3A3B", bg = "#4C3A3B" } # re, re
marker_marked = { fg = "#2E2E2E", bg = "#2E2E2E" } # cy-700, cy-700
marker_selected = { fg = "#595959", bg = "#595959" } # cy, cy

# Count
count_copied = { fg = "#595959", bold = true, reversed = true } # gr
count_cut = { fg = "#4C3A3B", bold = true, reversed = true } # re
count_selected = { fg = "#595959", bold = true, reversed = true } # cy

# Border
border_symbol = "│"
border_style = { fg = "#262933" } # ui

[indicator]
parent = { underline = true }
current = { fg = "#DFE5EA", bg = "#262933" } # tx, ui
preview = { underline = true }
padding = { open = "█", close = "█" }

[tabs]
active = { fg = "#DFE5EA", bg = "#404552", bold = true } # tx, ui-3
inactive = { fg = "#B0BFCB", bg = "#262933" } # tx-2, ui
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
# Normal mode
normal_main = { fg = "#DFE5EA", bg = "#404552", bold = true } # tx, ui-3
normal_alt = { fg = "#B0BFCB", bg = "#262933" } # tx-2, ui

# Select mode
select_main = { fg = "#111316", bg = "#595959", bold = true } # bg, cy
select_alt = { fg = "#595959", bg = "#1D1D23" } # cy, cy-900

# Unset mode
unset_main = { fg = "#111316", bg = "#595959", bold = true } # bg, cy
unset_alt = { fg = "#595959", bg = "#1D1D23" } # cy, cy-900

[status]
overall = { fg = "#DFE5EA" } # tx

# Permissions
perm_type = { fg = "#595959" } # bl
perm_read = { fg = "#B0BFCB" } # ye
perm_write = { fg = "#4C3A3B" } # re
perm_exec = { fg = "#595959" } # gr
perm_sep = { fg = "#B0BFCB" } # tx-2

# Progress
progress_label = { fg = "#111316" } # bg
progress_normal = { fg = "#595959", bg = "#2E2E2E" } # cy, cy-700
progress_error = { bg = "#4C3A3B" } # re

[which]
cols = 3
mask = { bg = "#1D1D23" } # bg-2
cand = { fg = "#595959", bold = true } # cy
rest = { fg = "#595959", italic = true } # cy
desc = { fg = "#718994" } # tx-3
separator = " "
separator_style = { }

[confirm]
border = { fg = "#404552" } # ui-3
title = { fg = "#718994", bold = true } # tx-3
body = { fg = "#DFE5EA", bold = true } # tx
list = { fg = "#DFE5EA" } # tx
btn_yes = { fg = "#DFE5EA", bg = "#404552", bold = true } # tx, ui-3
btn_no = { fg = "#B0BFCB", bg = "#262933" } # tx-2, ui

[spot]
border = { fg = "#404552" } # ui-3
title = { fg = "#718994", bold = true } # tx-3
tbl_col = { fg = "#B0BFCB" } # tx-2
tbl_cell = { fg = "#DFE5EA", bg = "#262933" } # tx, ui

[notify]
# Notification title
title_info = { fg = "#595959" } # bl
title_warn = { fg = "#695B57" } # or
title_error = { fg = "#4C3A3B" } # re

[pick]
border = { fg = "#404552", bold = true } # ui-3
active = { fg = "#DFE5EA" } # tx
inactive = { fg = "#B0BFCB" } # tx-2

[input]
border = { fg = "#404552" } # ui-3
title = { fg = "#718994", bold = true } # tx-3
value = { fg = "#DFE5EA" } # tx
selected = { bg = "#1D1D23" } # bg-2

[cmp]
border = { fg = "#404552", bold = true } # ui-3
active = { fg = "#DFE5EA", bg = "#262933" } # tx, ui
inactive = { fg = "#B0BFCB" } # tx-2

[tasks]
border = { fg = "#404552" } # ui-3
title = { fg = "#718994", bold = true } # tx-3
hovered = { fg = "#DFE5EA", bg = "#262933" } # tx, ui

[help]
on = { fg = "#595959" } # bl
run = { fg = "#595959" } # cy
desc = { fg = "#718994", italic = true } # tx-3
hovered = { bg = "#262933" } # ui
footer = { fg = "#111316", bg = "#595959", bold = true } # bg, cy

[filetype]
rules = [
  # Empty files
  { mime = "inode/empty", fg = "#718994" }, # tx-3

  # Special files
  { url = "*", is = "orphan", fg = "#718994" }, # tx-3
  { url = "*/", is = "orphan", fg = "#718994" }, # tx-3
  { url = "*", is = "link", fg = "#595959" }, # cy
  { url = "*/", is = "link", fg = "#595959" }, # cy
  { url = "*", is = "block", fg = "#DFE5EA" }, # tx
  { url = "*", is = "char", fg = "#DFE5EA" }, # tx
  { url = "*", is = "fifo", fg = "#4C3A3B" }, # ma
  { url = "*", is = "sock", fg = "#4C3A3B" }, # ma
  { url = "*", is = "sticky", fg = "#DFE5EA" }, # tx
  { url = "*", is = "dummy", fg = "#718994" }, # tx-3

  # Fallback
  { url = "*/", fg = "#DFE5EA" }, # tx
  { url = "*", is = "exec", fg = "#595959" }, # gr
  { url = "*", fg = "#B0BFCB" } # tx-2
]

[icon]
dirs = [
  { name = ".config", text = "", fg = "#595959" }, # cy
  { name = ".git", text = "", fg = "#595959" }, # cy
  { name = ".github", text = "", fg = "#595959" }, # cy
  { name = ".npm", text = "", fg = "#595959" }, # cy
  { name = "Desktop", text = "", fg = "#595959" }, # cy
  { name = "Development", text = "", fg = "#595959" }, # cy
  { name = "Documents", text = "", fg = "#595959" }, # cy
  { name = "Downloads", text = "", fg = "#595959" }, # cy
  { name = "Library", text = "", fg = "#595959" }, # cy
  { name = "Movies", text = "", fg = "#595959" }, # cy
  { name = "Music", text = "", fg = "#595959" }, # cy
  { name = "Pictures", text = "", fg = "#595959" }, # cy
  { name = "Public", text = "", fg = "#595959" }, # cy
  { name = "Videos", text = "", fg = "#595959" } # cy
]
conds = [
  # Special files
  { if = "orphan", text = "", fg = "#718994" }, # tx-3
  { if = "link", text = "", fg = "#595959" }, # cy
  { if = "block", text = "", fg = "#DFE5EA" }, # tx
  { if = "char", text = "", fg = "#DFE5EA" }, # tx
  { if = "fifo", text = "", fg = "#4C3A3B" }, # ma
  { if = "sock", text = "", fg = "#4C3A3B" }, # ma
  { if = "sticky", text = "", fg = "#DFE5EA" }, # tx
  { if = "dummy", text = "", fg = "#718994" }, # tx-3

  # Fallback
  { if = "dir", text = "", fg = "#595959" }, # cy
  { if = "exec", text = "", fg = "#595959" }, # gr
  { if = "!dir", text = "", fg = "#B0BFCB" } # tx-2
]